Add secret check for iOS build

diff --git a/.github/workflows/build_ios_on_merge.yml b/.github/workflows/build_ios_on_merge.yml
--- a/.github/workflows/build_ios_on_merge.yml
+++ b/.github/workflows/build_ios_on_merge.yml
@@ -25,6 +25,10 @@ jobs:
           APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
           APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
         run: |
+          if [[ -z "$APPLE_ID_EMAIL" || -z "$APPLE_ID_PASSWORD" ]]; then
+            echo "Missing APPLE_ID_EMAIL or APPLE_ID_PASSWORD secrets."
+            exit 1
+          fi
           echo "$APPLE_ID_PASSWORD" | xcrun altool --store-password-in-keychain-item AC_PASSWORD -u "$APPLE_ID_EMAIL" -p @keychain:AC_PASSWORD
       - name: Build iOS app
         run: flutter build ipa --release --export-options-plist ios/exportOptions.plist
